### ISSUE TITLE
Fix bundler

### ISSUE THREAD

**Issue by colgin** [harrytran998/rep-vite-bunlder-vue-ts#1]
Remove the plugins in rollupOptions, and declare it as a "vitePlugin", it works.

```typescript
import vue from '@vitejs/plugin-vue'
import rollupTs from 'rollup-plugin-typescript2'
import path from 'path'
import type { ConfigEnv, UserConfig } from 'vite'

const resolvePath = (p) => path.resolve(__dirname, p)

// https://vitejs.dev/config/
export default ({ command, mode }: ConfigEnv): UserConfig => ({
  plugins: [
    vue(),
    {
      ...rollupTs({
        check: true,
        tsconfig: path.resolve(__dirname, `tsconfig.json`), // your tsconfig.json path
        tsconfigOverride: {
          compilerOptions: {
            sourceMap: false,
            declaration: true,
            declarationMap: false,
          },
        },
      }),
      enforce: 'pre',
    },
  ],
  build: {
    minify: mode === 'production',
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'AButton',
    },
    rollupOptions: {
      // Maybe you don't need to declare input in rollupOptions, because you have declared it in lib
      // input: resolvePath('src/index.ts'),
      // plugins: [
      //   rollupTs({
      //     check: true,
      //     tsconfig: path.resolve(__dirname, `tsconfig.json`), // your tsconfig.json path
      //     // tsconfigOverride: {
      //     //   compilerOptions: {
      //     //     sourceMap: false,
      //     //     declaration: true,
      //     //     declarationMap: false,
      //     //   },
      //     // },
      //   }),
      // ],
      external: ['vue'],
      output: [
        {
          format: 'cjs',
          dir: undefined,
          file: './dist/index.js',
        },
        {
          format: 'es',
          dir: undefined,
          file: './dist/index.mjs',
        },
      ],
    },
  },
})

```

**Comment by nhattran998** [comment]
@colgin You can pull this code and run! I tried and still not work 😅

**Comment by colgin** [comment]
I pull the code, and run

```bash
yarn
yarn build
```
it looks good.
<img width="438" alt="截屏2021-05-20 上午9 27 03" src="https://user-images.githubusercontent.com/18627853/118905090-a6621c00-b94d-11eb-92bd-ed8c663181d4.png">

if you get error, you can post a image to show what the error is

**Comment by colgin** [comment]
Hi, there, rollup-plugin-typescript2 doesn't work well with pnpm, [issue](https://github.com/ezolenko/rollup-plugin-typescript2/issues/234).
use yarn or npm, everything works well.

**Comment by nhattran998** [comment]
> Hi, there, rollup-plugin-typescript2 doesn't work well with pnpm, [issue](https://github.com/ezolenko/rollup-plugin-typescript2/issues/234).
> use yarn or npm, everything works well.

Oh ... Thank you so much <3! LOL I don't think it's issue of pnpm :(

**Comment by nhattran998** [comment]
> Hi, there, rollup-plugin-typescript2 doesn't work well with pnpm, [issue](https://github.com/ezolenko/rollup-plugin-typescript2/issues/234).
> use yarn or npm, everything works well.

Btw, can I ask you a question? How do you know this is the problem with the plugin order of Vite?

**Comment by colgin** [comment]
It depends on how vite process the input accroding your configuration.
If you place the tsPlugin in rollupOptions.plugins, according the error, .vue file didn't produce the type file correctly, plain .ts file can produce the right type file.

So I guess plugins in rollupOptions only applied to some processed files(.vue files was translated to normal .js file without any type), after that, I spend some time to figure out if there is a way to apply tsPlugin to original file, including read the source code and [doc](https://vitejs.dev/guide/api-plugin.html#plugin-ordering).

Vite plugin extends rollup's plugin interface, according the doc, plugin specified enfore as 'pre' will be applied before plugin without enfore value. 

btw, I don’t know if this solution will bring any side effects, in my current opinion, it is good
